[package]
name = "nadja"
version = "0.1.0"
authors = ["Julien Eudine <julien@eudine.fr>"]
edition = "2018"
readme = "README.adoc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5"
