= Nadja (WIP)

A hardware description language using Rust syntax, combined with an event-driven simulator.

This library uses features only available in *Nightly Rust*. Please use the *nightly toolchain* to build the library.

== TODO

* Add a stop function
* Add a notion of time scale (ps, ns...)
* Enable submodules
* RAM block
* FSM
* Moore & Mealy machine
* Generate trace files
* macros for concat
* Generate SystemVerilog code
* Directly jump to dates at which there are events

== Usage (WIP)

Complete examples are available in the `examples/` directory:

* Fibonacci LFSR

=== Channels

Each node of a circuit can be represented by a variable implementing the `Channel<T>` trait (with `T`, the actual type of the circuit node). For instance, the `Signal<T>` and the `Wire<T>` structures both implement the `Channel<T>` trait. This trait is hidden by the library and you usually don't have to think about it.

=== Combinational logic

In Nadja, the Combinational logic of a circuit is described using the functional semantic.

Since the output of a combinational circuit is a pure function of the present inputs only, you can describe this kind of circuit by creating a function preceded by the attribute-like macro `#[channel]`. This kind of function is called a *Channel function*. The output type of the function should be the same as the output of your combinational circuit.

The name of channel functions should be written using the `UpperCamelCase`.

[source, rust]
----
#[channel]
fn MyChannelFunc(input1: type_i1, input2: type_i2) -> type_o {
    //Body of the channel function
}
----

You can use a struct literal expression to instantiate the combinational circuit. This instance implements the `Channel<T>` trait. For each input, you have to provide a reference that implements the `Channel<T>` trait representing the actual input of your combinational circuit.

[source, rust]
----
let output = MyChannelFunc { input1: &i1, input2: &i2 };
//i1,i2 & output implement the Channel<T> trait
----

=== Sequential logic

*Example:*

[source, rust]
----
#[seq]
mod my_module {
    //Constant parameter
    const INIT: usize = val_init;
    const WIDTH: usize = val_width;

    struct io {
        //Input
        a_i: In<ty_i1>,
        rst_ni: In<Logic>,

        //Output
        x_o: Out<VLogic<WIDTH>>,
        y_o: Out<ty_o2>,
    }

    fn core() {
        //Process
        let x_q: WIDTH = FF(x_d, rst_ni, INIT);
        //Channel function
        let x_d = CFunc1 {input: x_q};
        let y = CFunc2 {input: a_i};
        //Output
        Output {
            x_o: x_q,
            y_o: y,
        };
    }
}
----
